app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000
      - https://d34fb2fe21ff.ngrok-free.app
  mp:
    redirect-uri: https://d34fb2fe21ff.ngrok-free.app/mp/callback
  api:
    uri: http://localhost:8080